### ISSUE TITLE
Improvements in Fork

### ISSUE THREAD

**Issue by jvtrigueros** [shalecraig/vagrant-pebble#3]
I have forked this project and made a lot of changes to it. Mostly because it didn't fit my needs and I wanted to start using SDK 3. I don't know if you're interested in having me submit a PR so that it all stays in this repo or if the changes are too great that I should just keep them in my own fork.

Please check it out and let me know if you would like us to merge at some point.

**Comment by cpwc** [comment]
Do issue a pull request :smile:

**Comment by shalecraig** [comment]
Please do! That would be amazing!

**Comment by shalecraig** [comment]
Closing, since it looks like the PR was merged.

Thanks!
